{
 "title": "AdGuard Home Exporter",
 "description": "This is a AdGuard Home dashboard when using the https://github.com/henrywhitaker3/adguard-exporter Prometheus exporter",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "label_values(adguard_running,server)"
   }
  ]
 },
 "panels": [
  {
   "title": "AdGuard Home",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_running{server=\"$server\"}",
     "legendFormat": "{{ legend }}"
    }
   ]
  },
  {
   "title": "DHCP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_dhcp_enabled{server=\"$server\"}",
     "legendFormat": "{{ legend }}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_running{server=\"$server\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "% ads blocked",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(adguard_queries_blocked{server=\"$server\"}/ adguard_queries{server=\"$server\"}) * 100"
    }
   ]
  },
  {
   "title": "Top queries by domain",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, adguard_top_queried_domains{server=\"$server\"})",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Top Clients",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, adguard_top_clients{server=\"$server\"})",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "Top Blocked Domains",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(15, sum by (domain) (adguard_top_blocked_domains))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS queries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(adguard_queries{server=\"$server\"})",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Upstreams",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "topk(15, sum by (upstream) (adguard_top_upstreams{server=\"$server\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "adguard_top_upstreams_avg_response_time_seconds{server=\"$server\"}",
     "legendFormat": "{{upstream}}"
    }
   ]
  },
  {
   "title": "Ads blocked",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(adguard_queries_blocked{server=\"$server\"})",
     "legendFormat": "Filter lists"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "topk(15, sum by (client) (adguard_top_clients{server=\"$server\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Blocked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    (\n        adguard_blocked_filtered{server=\"$server\"}\n        +\n        adguard_blocked_safesearch{server=\"$server\"}\n        +\n        adguard_blocked_safebrowsing{server=\"$server\"}\n    ) \n    / adguard_queries{server=\"$server\"}\n) * 100",
     "legendFormat": "Blocked"
    }
   ]
  },
  {
   "title": "Top queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "topk(15, sum by (domain) (adguard_top_queried_domains))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DHCP Leases",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "adguard_dhcp_leases{server=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}